### PR TITLE
MinGW Support

### PR DESCRIPTION
**Pull request by Starz0r**
Decided I'd add in Windows support for fun and to learn. Wasn't too hard, and this obviously only supports MinGW, so no MSVC. Although it probably wouldn't be difficult to just open this project in Visual Studio and compile it there.

### CODE REVIEW

**Review by PQCraft — CHANGES_REQUESTED** [review]
Thank you for contributing! The code is fine but the compile script returns:
`gcc: error: unrecognized command line option ‘-mwindows’`
Also, sorry for not reviewing this earlier, I am currently juggling school and I have barely any time to do anything.

**Comment by Starz0r** [comment]
What version of GCC are you using? This works for me on version 8.3.0. You also don't need the `-mwindows` flag, it's pretty much only for disabling the console window when opening the application.

**Comment by PQCraft** [comment]
@Starz0r I'm using `gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0` according to `gcc --version`

**Comment by Starz0r** [comment]
It looks you aren't using the MinGW version of GCC which is probably why that flag doesn't exist.

**Pull request closed without merging**
